# Generated by Django 5.0.1 on 2025-02-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_transaction_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='date',
            field=models.DateField(),
        ),
    ]
