# Generated by Django 5.0.1 on 2025-02-22 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
