# Generated by Django 5.1.6 on 2025-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_sharedexpense_expensesplit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesplit',
            old_name='amount_owed',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sharedexpense',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='is_settled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
